const LOADING = "Loading";
const SHOW_NEWS = "SHOW_NEWS";
const ASK_NEWS = "ASK_NEWS";
const TOP_NEWS = "TOP_NEWS";
const JOB_NEWS = "JOB_NEWS";
const RESULT = "RESULT";
const GET_PROFILE_INFO = "GET_PROFILE_INFO";
const SEARCH_RESULT = "SEARCH_RESULT";
export const constants = {
  LOADING,
  SHOW_NEWS,
  ASK_NEWS,
  TOP_NEWS,
  JOB_NEWS,
  RESULT,
  GET_PROFILE_INFO,
  SEARCH_RESULT,
};
